- name: Java Install and set JAVA_HOME   
  hosts: Test

  tasks:
        - name: Add repo
          apt:
            name: software-properties-common

        - name: add java PPA
          apt_repository:
            repo: 'ppa:webupd8team/java'
            state: present

        - name: Automatically select the Oracle License
          shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections


        - name: install jdk
          apt:
            name: "oracle-java8-installer"
            update-cache: yes
            force: yes

        - name: Set JAVA_HOME
          lineinfile:
            dest: /etc/environment
            regexp: 'JAVA_HOME'
            line: 'JAVA_HOME=/usr/lib/jvm/java-8-oracle'
